### ISSUE TITLE
为什么训练先变好后变差？

### ISSUE THREAD

**Issue by zhukai2016** [LinXueyuanStdio/LaTeX_OCR_PRO#10]
`
当Epoch 400/600左右时，效果最好，BLEU-4 is 71、EditDistance is 73、  ExactMatchScore is 13、perplexity is 1.6，,然后下降，
最终结果Eval:  BLEU-4 is 16.43  ||  perplexity is -10.54  ||  EditDistance is 30.22  ||  ExactMatchScore is 0.00 

`

**Comment by zhukai2016** [comment]
> 
![选区_013](https://user-images.githubusercontent.com/20518866/68657001-cc934880-056d-11ea-9c15-19db311167e2.png)

**Comment by LinXueyuanStdio** [comment]
自己稍微调一下参，取batchsize=1

你这后面已经严重过拟合了，为什么还要继续训练，早停呀
