### ISSUE TITLE
ExactMatchScore参数始终为0是什么原因呢，求大神指点

### ISSUE THREAD

**Issue by jeremycurrygit** [LinXueyuanStdio/LaTeX_OCR_PRO#11]
![图片](https://user-images.githubusercontent.com/13865358/69112263-c72c8580-0aba-11ea-994a-0a8e5b6808c8.png)
![图片](https://user-images.githubusercontent.com/13865358/69112292-db708280-0aba-11ea-9e4b-8b979130b6de.png)
![图片](https://user-images.githubusercontent.com/13865358/69112334-ec20f880-0aba-11ea-8e07-bfa42de577a8.png)
![图片](https://user-images.githubusercontent.com/13865358/69112348-f3480680-0aba-11ea-82d6-10fb438d56b4.png)
![图片](https://user-images.githubusercontent.com/13865358/69112399-15418900-0abb-11ea-9902-d5e1953cb813.png)

**Comment by LinXueyuanStdio** [comment]
初始的learningrate太小了，这几乎没收敛啊

**Comment by jeremycurrygit** [comment]
> 
> 
> 初始的learningrate太小了，这几乎没收敛啊

将lr调整为0.1，loss很大
![图片](https://user-images.githubusercontent.com/13865358/69128541-81d27d00-0ae7-11ea-9062-3747ccdf2a32.png)
这种情况是正常的吗

**Comment by LinXueyuanStdio** [comment]
lr_init=0.1

lr_min=1e-5

lr_warm=1e-3

用这个试试看，一开始loss很大没关系，一个epoch用70000数据的话，一个epoch EM就应该有20吧。

你多调一下参数，练练丹。

**Comment by jeremycurrygit** [comment]
> 
> 
> lr_init=0.1
> 
> lr_min=1e-5
> 
> lr_warm=1e-3
> 
> 用这个试试看，一开始loss很大没关系，一个epoch用70000数据的话，一个epoch EM就应该有20吧。
> 
> 你多调一下参数，练练丹。

嗯嗯 谢谢 我试试

**Comment by CaiHandsome** [comment]
> > lr_init=0.1
> > lr_min=1e-5
> > lr_warm=1e-3
> > 用这个试试看，一开始loss很大没关系，一个epoch用70000数据的话，一个epoch EM就应该有20吧。
> > 你多调一下参数，练练丹。
> 
> 嗯嗯 谢谢 我试试

大佬您好，您的问题解决了吗？我尝试了了很多种都不行，能不能请教一下参数怎么调整。
