### ISSUE TITLE
训练的结果欠拟合怎么处理？

### ISSUE THREAD

**Issue by cx465164824** [LinXueyuanStdio/LaTeX_OCR_PRO#13]
我实验了3个数据集:full,hand,fullhand。但是训练的过程中，评估的标准都不如理想
 - Eval:  BLEU-4 is 9.93  ||  ExactMatchScore is 0.00  ||  EditDistance is 25.00  ||  perplexity is -6.04 
 - New best score (-2.55)!

三个数据集的评估结果都和上面大同小异，差别不大。
看过其他issue，尝试改动了学习率lr_init为0.1会导致训练时的perplexity持续增加到超过int上限变为负数。
请问一下是什么原因？怎么样操作可以复现你的训练结果？

**Comment by LinXueyuanStdio** [comment]
您好。我看了我的实验记录，emm，尴尬的是，lr_init=1e-4.....

完整的 training.json 如下

```json
{
    "export_name": "training.json",
    "device": "cuda:3",
    "criterion_method": "CrossEntropyLoss",
    "n_epochs": 600,
    "batch_size": 1,
    "dropout": 0.99,
    "clip": -1,
    "lr_method": "adam",
    "lr_scheduler": "CosineAnnealingLR",
    "lr_init": 1e-4,
    "lr_min": 1e-6,
    "start_decay": 6,
    "end_decay": 13,
    "lr_warm": 1e-4,
    "end_warm": 0
}
```

**Comment by LinXueyuanStdio** [comment]
可以参考一下我的 training.json，不过你要灵活一点。

因为在训练过程中我可能会根据模型的训练情况，手动调节一些参数（training.json 里的差不多都调过），然后再恢复继续训练，具体细节记不清了，上面的是一个最终版。

由于模型本身具有一定的随机性，即使是相同的超参数，最后的结果可能比我的高或者低。

所以，最后还是要靠你自己实践、炼丹......

**Comment by cx465164824** [comment]
好的谢谢，我尝试下...

**Comment by jeremycurrygit** [comment]
> 
> 
> 我实验了3个数据集:full,hand,fullhand。但是训练的过程中，评估的标准都不如理想
> 
>     * Eval:  BLEU-4 is 9.93  ||  ExactMatchScore is 0.00  ||  EditDistance is 25.00  ||  perplexity is -6.04
> 
>     * New best score (-2.55)!
> 
> 
> 三个数据集的评估结果都和上面大同小异，差别不大。
> 看过其他issue，尝试改动了学习率lr_init为0.1会导致训练时的perplexity持续增加到超过int上限变为负数。
> 请问一下是什么原因？怎么样操作可以复现你的训练结果？

我训练的情况和你的类似

**Comment by cx465164824** [comment]
> 可以参考一下我的 training.json，不过你要灵活一点。
> 
> 因为在训练过程中我可能会根据模型的训练情况，手动调节一些参数（training.json 里的差不多都调过），然后再恢复继续训练，具体细节记不清了，上面的是一个最终版。
> 
> 由于模型本身具有一定的随机性，即使是相同的超参数，最后的结果可能比我的高或者低。
> 
> 所以，最后还是要靠你自己实践、炼丹......

config_eval = Config({
            "dir_answers": self._dir_output + "formulas_val/",
            "batch_size": config.batch_size + 20
        })

我修改batch_size的时候，跑了一个epoch就挂了，我看到验证集这里把batch_size扩大了20，是有什么原因吗？

**Comment by LinXueyuanStdio** [comment]
验证过程不参与网络训练，但是验证集约为训练集的1/5，跑一次太久了，把batchsize扩大有利于节省时间且不会对模型造成影响

**Comment by LinXueyuanStdio** [comment]
这个20看你的机器而定，GPU内存大一点可以取一个大一点的数，GUP小就取小一点的数，不要OOM就好了

**Comment by cx465164824** [comment]
我在fullhand数据集上训练，loss在2左右无法收敛，我想加快训练，调节batch_size为2就oom了，有其他可调参数吗？

**Comment by LinXueyuanStdio** [comment]
barch_size=1呀，还oom的话只能修改model.json减少模型参数量，或者data.json减小数据集

**Comment by cx465164824** [comment]
> barch_size=1呀，还oom的话只能修改model.json减少模型参数量，或者data.json减小数据集

1没问题，但是1训练太慢了，所有数据都迭代一次要2个小时，所以看看能否加速训练，但是调到2就oom了...
