### ISSUE TITLE
模型欠拟合，loss在2左右很缓慢的下降

### ISSUE THREAD

**Issue by jeremycurrygit** [LinXueyuanStdio/LaTeX_OCR_PRO#14]
模型欠拟合，loss在2左右很缓慢的下降
![图片](https://user-images.githubusercontent.com/13865358/69312566-4e6c2b80-0c6a-11ea-850e-2bb2c6044d29.png)
![图片](https://user-images.githubusercontent.com/13865358/69312605-6643af80-0c6a-11ea-9ac6-4b5f74c59293.png)
batch_size dropout lr_method lr_init lr_min这些参数都做过一些调整，目前loss很缓慢的下降，似乎很难突破2的样子，是训练次数不够吗，有什么参数调整会有显著的提高呢 @LinXueyuanStdio求大神指点

**Comment by jeremycurrygit** [comment]
> 
> 
> 模型欠拟合，loss在2左右很缓慢的下降
> ![图片](https://user-images.githubusercontent.com/13865358/69312566-4e6c2b80-0c6a-11ea-850e-2bb2c6044d29.png)
> ![图片](https://user-images.githubusercontent.com/13865358/69312605-6643af80-0c6a-11ea-9ac6-4b5f74c59293.png)
> batch_size dropout lr_method lr_init lr_min这些参数都做过一些调整，目前loss很缓慢的下降，似乎很难突破2的样子，是训练次数不够吗，有什么参数调整会有显著的提高呢 @LinXueyuanStdio求大神指点

数据集问题 已解决

**Comment by liufeihongkkk** [comment]
你好，可以问下数据集是啥问题吗？我和你遇到相同问题了
