### ISSUE TITLE
Some machines have an issue of magick policy issues

### ISSUE THREAD

**Issue by chxiaoxn** [LinXueyuanStdio/LaTeX_OCR_PRO#22]
See https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion

**Comment by LinXueyuanStdio** [comment]
You can use the data in https://github.com/LinXueyuanStdio/Data-for-LaTeX_OCR where holds the full datasets.
Or you have to solve the issue of magick yourself.
We have no idea to help.
