### ISSUE TITLE
请问一下，语法树的抽取为什么不用Python实现呢？

### ISSUE THREAD

**Issue by songyuc** [LinXueyuanStdio/LaTeX_OCR_PRO#27]
尊敬的开发者，你好，请问一下，语法树的抽取为什么不用Python实现呢？
期待你的回复！

**Comment by LinXueyuanStdio** [comment]
python没有好用的解析 latex 的包

python里解析 latex 的需求不常见，常见的是前端解析 latex 并显示，所以选择了 katex，katex是前端渲染 latex 相对友好的了
