### ISSUE TITLE
请问这个项目是怎么用的呢？小白没太看明白

### ISSUE THREAD

**Issue by LSJds** [LinXueyuanStdio/LaTeX_OCR_PRO#3]
请问这个项目是怎么用的呢？小白没太看明白..........mathpix太贵了，想找个替代的

**Comment by LinXueyuanStdio** [comment]
这个项目并没有提供像mathpix的有界面的应用，而是提供识别数学公式的模型、数据及相关的处理方法。可以自己下载数据训练自己的模型。

如果是想要落地一个类似mathpix的应用，那请自己搞。
