### ISSUE TITLE
关于数据和预训练模型

### ISSUE THREAD

**Issue by albertyou2** [LinXueyuanStdio/LaTeX_OCR_PRO#34]
@LinXueyuanStdio 
你好，我下载你的代码 训练提示无法运行
我发现data已经移除这个库了，
然后GIT一直无法下载，请问有没有网盘或者其他链接可以下载?i谢谢

然后能否提供一个预训练模型呢？非常感谢！

**Comment by LinXueyuanStdio** [comment]
可以手动下载这个项目地址的zip包，手动解压到data下
https://github.com/LinXueyuanStdio/Data-for-LaTeX_OCR

数据不会上传到网。有需求可以让能下载的大佬分享。

大佬可以分享网盘的链接在issue或者pr到README里，请随意。我只帮忙合并。

我个人是不会把数据上传给网盘的。
