### ISSUE TITLE
Why perplexity is negative?

### ISSUE THREAD

**Issue by JackyLiu-SCUT** [LinXueyuanStdio/LaTeX_OCR_PRO#36]
Why perplexity is negative? By definition it is 2 to the power H(x), which is always positive. And I think there is no problem in the training result nor the codes.

Looking forward to be educated and discusssing with everyone interested in this project! ^_^ I am a college student who just enter this cv field and select this domain as my graduation project.

![image](https://user-images.githubusercontent.com/51254222/111122787-7b53f880-85a9-11eb-8d3f-3323a7ab9d5b.png)

**Comment by LinXueyuanStdio** [comment]
Wow, you got a high exact match score! Good job!
In this project, perp = - np.exp(ce_words / float(n_words))

**Comment by JackyLiu-SCUT** [comment]
> Wow, you got a high exact match score! Good job!
> In this project, perp = - np.exp(ce_words / float(n_words))

Thank you for replying! I am a rookie in programming and your reply helps me understand a lot!

Another question I want to ask before closing this issue:

In data.json there is an attribute named **max_iter**, and the default value is 5000. Does it mean even if I have 10k samples in training set, but it just uses 5k in training?

**Comment by LinXueyuanStdio** [comment]
YES.

**Comment by JackyLiu-SCUT** [comment]
Thank you for replying! Closing the issue now.
