### ISSUE TITLE
my 4 scores are abnormal , i dont know why for the 0.00  of ExactMatchScore when i run the 3rd Epoch

### ISSUE THREAD

**Issue by liufeihongkkk** [LinXueyuanStdio/LaTeX_OCR_PRO#37]
![Screenshot 2021-03-18 175105](https://user-images.githubusercontent.com/20340182/111607010-ce7cb400-8812-11eb-8fc5-acb21b2f4778.png)

**Comment by LinXueyuanStdio** [comment]
don't worry. it is healthy because training is quite slow. just continue to run the rest epochs
