### ISSUE TITLE
关于pytorch和tensorflow

### ISSUE THREAD

**Issue by Renjie1997** [LinXueyuanStdio/LaTeX_OCR_PRO#40]
首先谢谢您。
请问img2seq_torch可以直接训练吗，效果和tensorflow的比较起来那个更好一点呢
谢谢。

**Comment by LinXueyuanStdio** [comment]
您好，不可以
img2seq_torch效果不好，就没有进一步测试了
tensorflow支持输入不确定长宽的图片，用bucket很爽，但是torch必须写死长宽

**Comment by Renjie1997** [comment]
> 您好，不可以
> img2seq_torch效果不好，就没有进一步测试了
> tensorflow支持输入不确定长宽的图片，用bucket很爽，但是torch必须写死长宽

谢谢，确实是这样，谢谢。还有个问题，为什么测试的时候，测试10张图片，如果一张图片作为一个batch，速度很慢（一张图片要0.06秒左右）而10张图片一起作为一个batch,速度非常快（10张一共耗时0.1秒）。但是如果10张作为一个batch, 这10张图片必须scale到最大的size。是因为tensorflow在预测的时候对于不同大小的图片在建立不同的图吗? 谢谢

**Comment by LinXueyuanStdio** [comment]
> > 您好，不可以
> > img2seq_torch效果不好，就没有进一步测试了
> > tensorflow支持输入不确定长宽的图片，用bucket很爽，但是torch必须写死长宽
> 
> 谢谢，确实是这样，谢谢。还有个问题，为什么测试的时候，测试10张图片，如果一张图片作为一个batch，速度很慢（一张图片要0.06秒左右）而10张图片一起作为一个batch,速度非常快（10张一共耗时0.1秒）。但是如果10张作为一个batch, 这10张图片必须scale到最大的size。是因为tensorflow在预测的时候对于不同大小的图片在建立不同的图吗? 谢谢

不是的，是一个batch内的张量形状必须一致，方便进行张量运算。而对于张量运算，tensorflow可以并行加速的。

**Comment by Renjie1997** [comment]
> > > 您好，不可以
> > > img2seq_torch效果不好，就没有进一步测试了
> > > tensorflow支持输入不确定长宽的图片，用bucket很爽，但是torch必须写死长宽
> > 
> > 
> > 谢谢，确实是这样，谢谢。还有个问题，为什么测试的时候，测试10张图片，如果一张图片作为一个batch，速度很慢（一张图片要0.06秒左右）而10张图片一起作为一个batch,速度非常快（10张一共耗时0.1秒）。但是如果10张作为一个batch, 这10张图片必须scale到最大的size。是因为tensorflow在预测的时候对于不同大小的图片在建立不同的图吗? 谢谢
> 
> 不是的，是一个batch内的张量形状必须一致，方便进行张量运算。而对于张量运算，tensorflow可以并行加速的。
好的，谢谢，我尝试换了网络，但是发现vgg或者Resnet等网络反而效果不如原始的简单的网络（loss很难收敛），但是densenet效果挺好的，是因为较深的网络不适合公式上下关系的学习吗？

**Comment by Renjie1997** [comment]
好的，谢谢，我尝试换了网络，但是发现vgg或者Resnet等网络反而效果不如原始的简单的网络（loss很难收敛），但是densenet效果挺好的，是因为较深的网络不适合公式上下关系的学习吗？

**Comment by LinXueyuanStdio** [comment]
除非显式地对上下关系建模，否则没有任何证据表明网络能识别上下关系。
vgg、Resnet和densenet都是简单的通用架构，其中一个效果比其他的好，无法说明任何问题。
