### ISSUE TITLE
分支“dependabot/pip/tensorflow-gpu-2.3.1”环境问题

### ISSUE THREAD

**Issue by benzxiaojunjun** [LinXueyuanStdio/LaTeX_OCR_PRO#48]
环境要求tensorflow-gpu==2.3.1，tensorboard==1.12.2，但代码里好几处都需要导入tensorflow.contrib这个包，这个包好像在2.X版本里就不支持了，所以代码没法正常执行。
![image](https://user-images.githubusercontent.com/72971361/122502215-cb1ee180-d028-11eb-931e-20581c27dc3f.png)

**Comment by LinXueyuanStdio** [comment]
dependabot/pip/tensorflow-gpu-2.3.1 是机器人创造的分支，没有考虑整体的运行环境，不建议使用
