### ISSUE TITLE
Filename error when doing make small 

### ISSUE THREAD

**Issue by chiangqiqi** [LinXueyuanStdio/LaTeX_OCR_PRO#6]
Hi, I encounter this problem while running your code, like python could not find the data files needed. 

I dig into the code and found the config files like 

```
    "dir_images_train": "data/small/images/train/",
    "dir_images_test" : "data/small/images/test/",
    "dir_images_val"  : "data/small/images/val/",

    "path_matching_train": "data/small/matching/train.txt",
    "path_matching_val"  : "data/small/matching/test.txt",
    "path_matching_test" : "data/small/matching/val.txt",

    "path_formulas_train": "data/small/formulas/train.norm.txt",
    "path_formulas_test" : "data/small/formulas/test.norm.txt",
    "path_formulas_val"  : "data/small/formulas/val.norm.txt",
```

is not the same as the file  path in the data repo. like 

```
data/small/matching/train.matching.txt
```

Is this a bug or make small is deprecated now? 

I can send you a patch is this should be fixed.

**Comment by LinXueyuanStdio** [comment]
I feel so sorry that I have moved all data to [Data-for-LaTeX_OCR](https://github.com/LinXueyuanStdio/Data-for-LaTeX_OCR) which causes something wrong. 
It is just a bug. I would appreciate it if you submit a PR.

**Comment by chiangqiqi** [comment]
check the patch #7

**Comment by LinXueyuanStdio** [comment]
thanks
